/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tily' at '12/5/14 2:29 PM' with Gradle 2.2.1
 *
 * @author tily, @date 12/5/14 2:29 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
