/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'root' at '14/11/29 16:42' with Gradle 2.2
 *
 * @author root, @date 14/11/29 16:42
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
