/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tily' at '12/2/14 9:54 AM' with Gradle 2.2.1
 *
 * @author tily, @date 12/2/14 9:54 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
